dist: xenial

# Note: .NET aspects only present for current tooling
# (such as event registry generation)
language: csharp
mono: none
dotnet: 3.1

# We really don't need to see "Welcome to .NET Core" everywhere,
# and setting the TERM variable to "dumb" fixes some odd console
# output where dotnet appears to issue control characters (^[[?1h^[=) that
# Travis doesn't support.
env:
  global:
    - DOTNET_NOLOGO=true TERM=dumb

script:
  - ./travis.sh
