name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out our repo
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: |
        # Compile the protos to make sure they're valid
        ./build.sh

        # Ensure no diff
        git diff --exit-code README.md
