# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check Unexpected Changes
on: [pull_request]

jobs:
  check:
    if: github.actor != 'copybara-service[bot]'
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Generate the JSON Schema
      uses: ./.github/workflows/generate_jsonschema

    - name: Check for schema changes
      run: git diff --exit-code .

    - if: ${{ failure() }}
      run: |-
        echo "::error title=The JSON Schema changed!::If this is unexpected, update your branch or check for an open PR with schema changes"
        exit 1
