name: Generate
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Setup Node for gen/postgen scripts
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Setup Go for proto2jsonschema script
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    # Run the generators
    - run: ./scripts/gen.sh
    # Ensure there is no diff, otherwise we need to run the generator.
    - run: git diff --exit-code .
